# 389. Find the Difference
# Easy
# 4.6K
# 449
# Companies

# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

 

# Example 1:

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.

# Example 2:

# Input: s = "", t = "y"
# Output: "y"

 

# Constraints:

#     0 <= s.length <= 1000
#     t.length == s.length + 1
#     s and t consist of lowercase English letters.

# Accepted
# 613.5K
# Submissions
# 1M
# Acceptance Rate
# 60.2%

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:

        # lmap = {}

        # for letter in s :
        #     if letter in lmap:
        #         lmap[letter] += 1
        #     else :
        #         lmap[letter] = 1


        # for letter in t :
        #     if not letter in lmap :
               
        #         return letter 
        #     else :
        #         if lmap[letter] > 0 :
        #             lmap[letter] -= 1
        #         else :
        #             return letter

        
        total  = 0

        for letter in s :
            total+= ord(letter)

        for letter in t :
            total-= ord(letter)

        return chr(-total)

    


